---
title: "Publications"
output:
  html_document:
    includes:
      after_body: footer.html
---

<!-- A little trick I found online to make a new list that indents without bullet points --> 
<style>
.nobullet li {
  list-style-type: none;
}
</style>

An up-to-date list of my publications can also be found on my [Google Scholar](https://scholar.google.ca/citations?user=j-5nTf8AAAAJ&hl=en&oi=sra) page. Follow the DOI links below to download these papers from their respective journals. If you don't have access, feel free to [email me](mailto:timothy.thurman@mail.mcgill.ca) to request a copy. 
<br />

<br />

### Peer-reviewed:

<!-- Then, calling that new class to make indents for the list. Create the elements in the list with the 0., then add the number of each paper with X\., which escapes the period and allows it to be used. --> 
<div class="nobullet">

  0. 6\. **Thurman, T.J.**, Szejner-Sigal, A., McMillan, W.O. Movement of a *Heliconius* hybrid zone over 30 years: a Bayesian approach. Accepted at *Journal of Evolutionary Biology*.

  0. 5\. Hu, J., Askary, A.M., **Thurman, T.J.**, Spiller, D. Palmer, T.M., Pringle, R.M., Barrett, R.D.H. 2019. Epigenetic signatures of colonizing new environments in *Anolis* lizards. In press at *Molecular Biology and Evolution*. [<i class="ai ai-doi ai-lg"></i>](https://doi.org/10.1093/molbev/msz133)

  0. 4\. Pringle, R.M.\*, Kartzinel, T.R.\*, Palmer, T.M.\*, **Thurman, T.J.**, Fox-Dobbs, K., Xu, C.C.Y., Hutchinson, M.C., Coverdale, T.C., Daskin, J.H., Evangelista, D.A., Gotanda, K.M., Man in ’t Veld, N.A., Wegener, J.E., Kolbe, J.J., Schoener, T.W., Spiller, D.A., Losos, J.B., Barrett, R.D.H. 2019. Predator-induced collapse of niche structure and species coexistence. *Nature*, **570**(7759):58-64. [<i class="ai ai-doi ai-lg"></i>](https://doi.org/10.1038/s41586-019-1264-6)[<i class="ai ai-dryad ai-lg"></i>](https://doi.org/10.5061/dryad.2h87r1f)

  0. 3\. **Thurman, T.J.\***, Brodie, E.,* , Evans, E., McMillan, W.O. 2018. Facultative pupal mating in *Heliconius erato*: implications for mate choice, female preference and speciation. *Ecology and Evolution*, **8**(3):1882-1889. [<i class="ai ai-doi ai-lg"></i>](https://doi.org/10.1002/ece3.3624)[<i class="ai ai-dryad ai-lg"></i>](https://datadryad.org/resource/doi:10.5061/dryad.t0hd4/1)

  0. 2\. **Thurman, T.J.**, Barrett, R.D.H. 2016. The genetic consequences of selection in natural populations. *Molecular Ecology*, **27**(5):1429-1448. [<i class="ai ai-doi ai-lg"></i>](https://doi.org/10.1111/mec.13559)

  0. 1\. **Thurman, T.J.\***, Seymoure, B.* 2016. A bird's eye view of two mimetic tropical butterflies: coloration matches predator's sensitivity. *Journal of Zoology*, **298**(3):159-168. *Journal of Zoology* 2016 Paper of the Year. [<i class="ai ai-doi ai-lg"></i>](https://doi.org/10.1111/jzo.12305) Featured on the *Journal of Zoology* [blog](https://jzoblog.wordpress.com/2017/09/20/winners-of-the-2016-journal-of-zoology-paper-of-the-year-award-timothy-thurman-and-brett-seymoure/) and [podcast](https://zslpublications.onlinelibrary.wiley.com/hub/journal/14697998/podcasts).
</div>



\* indicates equal contributions of authors