---
title: "Research"
output:
  html_document:
    includes:
      after_body: footer.html
---


I study adaptation, the process by which populations of organisms evolve to be better suited to live in their environment. In particular, I try to link adaptation at the level of physical traits, or phenotypes, with an understanding of the underlying genetics. To do this, I combine approaches from organismal biology, field ecology, population genetics, genomics, and statistical modeling. I'm especially interested in understanding adaptation in natural populations, outside the laboratory. Thus, much of my research involves fieldwork (either collections or experiments) with non-model organisms. 

#### Current projects include:

* *Experimental evolution in Anolis lizards*- I study how *A. sagrei* lizards have evolved in response to the introduction of predator and competitor species as part of a large-scale, long-term field experiment in the Bahamas. This project is in collaboration with Dr. [Rob Pringle](https://pringle.princeton.edu) at Princeton University and Dr. [Todd Palmer](http://www.thepalmerlab.com/TMP/welcome.html) at the University of Florida.


* *Hybrid zone movement in Heliconius butterflies*- Repeated studies of hybrid zones (areas of contact between species or subspecies) allow biologists to understand how various evolutionary forces may change, or stay stable, through time. In eastern Panama there is a hybrid zone between two subspecies of *H. erato*. Originally studied in the 1980s, it was sampled again in the 1990s and found to have moved significantly. I'm part of a team that has again re-sampled the hybrid zone to understand its continued movement, and to determine the genetic and environmental causes driving hybrid zone movement in this species. 

